import pygame
from typing import Union, Callable, Dict, Tuple, Any


AnyVector = Union[Tuple[float, float], pygame.math.Vector2, Vector2]
EventDictType = Dict[int, Callable[[], None]]
Color = pygame.Color

EVENTDICT:EventDictType


class Vector2(pygame.math.Vector2):
    def int(self) -> Vector2: ...

class Game:
    def __init__(self, screenSize: tuple[int, int]) -> None:
        self.display: pygame.Surface = None
        self.clock: pygame.time.Clock = None
        self.running: bool = None
        self.tickCall: Callable[[int], None]
        self.drawCall: Callable[[], None]
        self.eventDict: EventDictType = None
        self.keyDownDict: Any = None
        ...
    def run(self) -> None: ...
    def tick(self) -> None: ...
    def draw(self) -> None: ...
    def handleEvents(self) -> None: ...
    def exit(self) -> None: ...
    def tickCall(self, dt: int) -> None: ...
    def drawCall(self) -> None: ...
    @staticmethod
    def setCaption(caption: str) -> None: ...


class Drawable:
    def __init__(self, display:pygame.Surface, pos:AnyVector) -> None:
        self.display: pygame.Surface = None
        self.pos: Vector2 = None
        ...
    def tick(self, dt:int) -> None: ...
    def draw(self) -> None: ...
    def moveTo(self, pos:AnyVector) -> None: ...
    def moveBy(self, offset:AnyVector) -> None: ...

class Image(Drawable):
    def __init__(self, display: pygame.Surface, pos:AnyVector, image:pygame.Surface) -> None:
        self.image: pygame.Surface = None
        ...
    def draw(self) -> None: ...

class Text(Drawable):
    def __init__(self, display:pygame.Surface, pos: AnyVector, text: str = "", font: pygame.font.Font = None,
                 fontColor: Color = None) -> None:
        self.font: pygame.font.Font = None
        self.text: str = None
        self.fontColor: Color = None
        ...
    def draw(self) -> None: ...
    def write(self, text: str) -> None: ...
    def clear(self) -> None: ...

class TextBox(Drawable):
    def __init__(self, display: pygame.Surface, pos: AnyVector, font: pygame.font.Font = None,
                 fontColor: Color = None) -> None:
        self.isActive: bool = None
        self.trueText: str = None
        ...
    def draw(self) -> None: ...
    def type(self, char: str) -> None: ...
