from .main import Drawable, AnyVector, Color, Event, Surface
import pygame
from typing import List


class Text(Drawable):
    def __init__(self, display:pygame.Surface, pos: AnyVector, text: str = "", font: pygame.font.Font = None,
                 font_color: Color = None, hitbox: pygame.Surface = None
                 ) -> None:
        self.font: pygame.font.Font = None
        self.text: str = None
        self.font_color: Color = None
        self.hitbox: pygame.Surface = None
        ...
    def draw(self) -> pygame.Surface: ...
    def get_text_lines_surfaces(self, font_color: Color = None) -> List[Surface]: ...
    def render_text(self, color: Color = None) -> pygame.Surface: ...
    def set_auto_hitbox(self) -> None: ...
    def write(self, text: str) -> None: ...
    def clear(self) -> None: ...

class TextBox(Text):
    def __init__(self, display: pygame.Surface, pos: AnyVector, font: pygame.font.Font = None,
                 font_color: Color = None, font_color_active: Color = None,
                 flexible_hitbox: bool = None) -> None:
        self.is_active: bool = None
        self.true_text: str = None
        self.font_color_active: Color = None
        self.flexible_hitbox: bool = None
        ...
    def type_text(self, char:str, key: int) -> None: ...
    def handle_events(self, event: Event) -> None: ...
    def draw(self) -> pygame.Surface: ...
